# force copy from tencent/tdesign
# å½“åœ¨ issue çš„ comment å›å¤ç±»ä¼¼ `Duplicate of #111` è¿™æ ·çš„è¯ï¼Œissue å°†è¢«è‡ªåŠ¨æ‰“ä¸Š é‡å¤æäº¤æ ‡ç­¾ å¹¶ä¸” cloese
name: Issue Add Assigness

on:
  issues:
    types: [opened, edited]

jobs:
  mark-duplicate:
    runs-on: ubuntu-latest
    steps:
      - name: 1è·å–ä¿¡æ¯ ä»“åº“/æ ‡é¢˜/  2 æ‹‰å–æ¥å£ è¾“å‡ºè´¡çŒ®è€…  3. assgin æˆ–è€… æé†’@;
        run: echo ${{github.event.issue.title}} 
      - name: 'ä»“åº“'
        run: |
          repository=${{github.repository}}
          project_name=${repository#*/}
          echo $repository $project_name
      - name: æ‹‰å€Ÿå£ åˆ¤æ–­ä»“åº“ ç»„ä»¶ è¾“å‡ºè´¡çŒ®è€…
        run: node index.js
      - name: Add assigness
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-assignees'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          assignees: '94dreamer'
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpened: |
            ğŸ‘‹ @{{ author }}
            æ‰¾åˆ°äº†ç»„ä»¶å¯¹æ¥äºº
            æ²¡æœ‰æ‰¾åˆ°å¯¹æ¥äººã€‚
            Thank you for raising an issue. We will will investigate into the matter and get back to you as soon as possible.
            Please make sure you have given us as much context as possible.
